lumo_file_version = "0.1.1"
software_version = "0.5.0"
description = "Default 6-node fNIRS device configuration"
version = "1.0.0"

[file_names]
recordingdata_file = "recordingdata.toml"
event_file = "events.toml"
hardware_file = "hardware.toml"
layout_file = "layout.json"
log_file = "lumo.log"

[[intensity_files]]
file_name = "intensity_01_6node.bin"
time_range = [100,189400]
